# Generated by Django 5.2.1 on 2025-05-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_network', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_hosts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHostResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac', models.CharField(blank=True, max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='network_scanner.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='network_scanner.scanhostresult')),
            ],
        ),
    ]
