# Generated by Django 5.2.1 on 2025-05-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_module_parent_alter_module_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['parent__id', 'name']},
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Clase de icono Bootstrap o FontAwesome', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
