# Generated by Django 5.2.1 on 2025-05-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_module_options_alter_module_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
