# Generated by Django 5.2.1 on 2025-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_module_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
