# Generated by Django 5.2.1 on 2025-05-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_investigator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationhistory',
            old_name='created_at',
            new_name='searched_at',
        ),
        migrations.RemoveField(
            model_name='investigationhistory',
            name='query_type',
        ),
        migrations.RemoveField(
            model_name='investigationhistory',
            name='result',
        ),
        migrations.RemoveField(
            model_name='investigationhistory',
            name='target',
        ),
        migrations.AddField(
            model_name='investigationhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='investigationhistory',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigationhistory',
            name='result_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investigationhistory',
            name='search_type',
            field=models.CharField(blank=True, choices=[('username', 'Nombre de usuario'), ('email', 'Correo electrónico'), ('fullname', 'Nombre completo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigationhistory',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='SherlockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sherlock_results', to='osint_investigator.investigationhistory')),
            ],
        ),
    ]
